// Automatic FlutterFlow imports
import '/backend/backend.dart';
import '/backend/schema/structs/index.dart';
import '/backend/supabase/supabase.dart';
import '/flutter_flow/flutter_flow_theme.dart';
import '/flutter_flow/flutter_flow_util.dart';
import 'index.dart'; // Imports other custom actions
import '/flutter_flow/custom_functions.dart'; // Imports custom functions
import 'package:flutter/material.dart';
// Begin custom action code
// DO NOT REMOVE OR MODIFY THE CODE ABOVE!

import 'index.dart'; // Imports other custom actions

import 'package:cloud_firestore/cloud_firestore.dart';

Future<String> importarEquipamentosFirebase() async {
  // Custom Action para importar equipamentos
  // Total: 89 equipamentos
  // Email: confecção@grupodass.com.br
  // Coleção: EQUIPAMENTOS_EMPRESA
  // SEM campo STATUS

  final FirebaseFirestore firestore = FirebaseFirestore.instance;
  final String collectionName = 'EQUIPAMENTOS_EMPRESA';

  // Lista com todos os 89 equipamentos
  final List<Map<String, dynamic>> equipamentos = [
    {
      "PATRIMONIO": "56193",
      "EQUIPAMENTO": "AR CONDICIONADO",
      "NOME": "AR CONDICIONADO",
      "MODELO": "SPLIT",
      "TIPO": "CONVENCIONAL",
      "MARCA": "ELETROLUX",
      "RESPONSAVEL": "",
      "TENSAO": "220 V",
      "FLUIDO": "R410A",
      "BTUS": "12K BTUS",
      "SETOR": "ADMINISTRATIVO",
      "SALA": "OCUPACIONAL",
      "EMAIL": "confecção@grupodass.com.br"
    },
    {
      "PATRIMONIO": "71109",
      "EQUIPAMENTO": "AR CONDICIONADO",
      "NOME": "AR CONDICIONADO",
      "MODELO": "SPLIT",
      "TIPO": "INVERTER",
      "MARCA": "LG",
      "RESPONSAVEL": "",
      "TENSAO": "220 V",
      "FLUIDO": "R410A",
      "BTUS": "22K BTUS",
      "SETOR": "ADMINISTRATIVO",
      "SALA": "ADM.DP",
      "EMAIL": "confecção@grupodass.com.br"
    },
    {
      "PATRIMONIO": "87311",
      "EQUIPAMENTO": "AR CONDICIONADO",
      "NOME": "AR CONDICIONADO",
      "MODELO": "SPLIT",
      "TIPO": "INVERTER",
      "MARCA": "LG",
      "RESPONSAVEL": "",
      "TENSAO": "220 V",
      "FLUIDO": "R410",
      "BTUS": "22K BTUS",
      "SETOR": "ADMINISTRATIVO",
      "SALA": "FISCAL/ CONTROLADORIA",
      "EMAIL": "confecção@grupodass.com.br"
    },
    {
      "PATRIMONIO": "60466",
      "EQUIPAMENTO": "AR CONDICIONADO",
      "NOME": "AR CONDICIONADO",
      "MODELO": "SPLIT",
      "TIPO": "CONVENCIONAL",
      "MARCA": "SPRINGER",
      "RESPONSAVEL": "",
      "TENSAO": "220 V",
      "FLUIDO": "R22",
      "BTUS": "12K BTUS",
      "SETOR": "ADMINISTRATIVO",
      "SALA": "ENFERMAGEM",
      "EMAIL": "confecção@grupodass.com.br"
    },
    {
      "PATRIMONIO": "93366",
      "EQUIPAMENTO": "AR CONDICIONADO",
      "NOME": "AR CONDICIONADO",
      "MODELO": "SPLIT",
      "TIPO": "INVERTER",
      "MARCA": "ELGIN",
      "RESPONSAVEL": "",
      "TENSAO": "220V",
      "FLUIDO": "R410",
      "BTUS": "12K BTUS",
      "SETOR": "ADMINISTRATIVO",
      "SALA": "ADM JURIDICO",
      "EMAIL": "confecção@grupodass.com.br"
    },
    {
      "PATRIMONIO": "41143",
      "EQUIPAMENTO": "AR CONDICIONADO",
      "NOME": "AR CONDICIONADO",
      "MODELO": "SPLIT",
      "TIPO": "CONVENCIONAL",
      "MARCA": "ELGIN",
      "RESPONSAVEL": "",
      "TENSAO": "220 V",
      "FLUIDO": "R22",
      "BTUS": "12K BTUS",
      "SETOR": "ADMINISTRATIVO",
      "SALA": "QUARTO MOTORISTA",
      "EMAIL": "confecção@grupodass.com.br"
    },
    {
      "PATRIMONIO": "87386",
      "EQUIPAMENTO": "AR CONDICIONADO",
      "NOME": "AR CONDICIONADO",
      "MODELO": "SPLIT",
      "TIPO": "INVERTER",
      "MARCA": "LG",
      "RESPONSAVEL": "",
      "TENSAO": "220 V",
      "FLUIDO": "R410A",
      "BTUS": "22K BTUS",
      "SETOR": "ADMINISTRATIVO",
      "SALA": "RH",
      "EMAIL": "confecção@grupodass.com.br"
    },
    {
      "PATRIMONIO": "111051",
      "EQUIPAMENTO": "AR CONDICIONADO",
      "NOME": "AR CONDICIONADO",
      "MODELO": "SPLIT",
      "TIPO": "INVERTER",
      "MARCA": "GREE",
      "RESPONSAVEL": "",
      "TENSAO": "220 V",
      "FLUIDO": "R410A",
      "BTUS": "12K BTUS",
      "SETOR": "ADMINISTRATIVO",
      "SALA": "ADM",
      "EMAIL": "confecção@grupodass.com.br"
    },
    {
      "PATRIMONIO": "111052",
      "EQUIPAMENTO": "AR CONDICIONADO",
      "NOME": "AR CONDICIONADO",
      "MODELO": "SPLIT",
      "TIPO": "INVERTER",
      "MARCA": "GREE",
      "RESPONSAVEL": "",
      "TENSAO": "220 V",
      "FLUIDO": "",
      "BTUS": "12K BTUS",
      "SETOR": "ADMINISTRATIVO",
      "SALA": "AMBULATÓRIO",
      "EMAIL": "confecção@grupodass.com.br"
    },
    {
      "PATRIMONIO": "87606",
      "EQUIPAMENTO": "AR CONDICIONADO",
      "NOME": "AR CONDICIONADO",
      "MODELO": "SPLIT",
      "TIPO": "INVERTER",
      "MARCA": "LG",
      "RESPONSAVEL": "",
      "TENSAO": "220V",
      "FLUIDO": "R410A",
      "BTUS": "11.5K BTUS",
      "SETOR": "ADMINISTRATIVO",
      "SALA": "TREINAMENTO ADM",
      "EMAIL": "confecção@grupodass.com.br"
    },
    {
      "PATRIMONIO": "108104",
      "EQUIPAMENTO": "AR CONDICIONADO",
      "NOME": "AR CONDICIONADO",
      "MODELO": "SPLIT",
      "TIPO": "INVERTER",
      "MARCA": "ELGIN",
      "RESPONSAVEL": "",
      "TENSAO": "220V",
      "FLUIDO": "R410A",
      "BTUS": "18K BTUS",
      "SETOR": "CORTE",
      "SALA": "CORTE ADM",
      "EMAIL": "confecção@grupodass.com.br"
    },
    {
      "PATRIMONIO": "104000",
      "EQUIPAMENTO": "AR CONDICIONADO",
      "NOME": "AR CONDICIONADO",
      "MODELO": "SPLIT",
      "TIPO": "INVERTER",
      "MARCA": "ELGIN",
      "RESPONSAVEL": "",
      "TENSAO": "220V",
      "FLUIDO": "R410A",
      "BTUS": "24K BTUS",
      "SETOR": "ALMX",
      "SALA": "SALA IMPRESSÃO",
      "EMAIL": "confecção@grupodass.com.br"
    },
    {
      "PATRIMONIO": "144183",
      "EQUIPAMENTO": "AR CONDICIONADO",
      "NOME": "AR CONDICIONADO",
      "MODELO": "SPLIT",
      "TIPO": "INVERTER",
      "MARCA": "ELGIN",
      "RESPONSAVEL": "",
      "TENSAO": "220 V",
      "FLUIDO": "R410A",
      "BTUS": "12K BTUS",
      "SETOR": "ADMINISTRATIVO",
      "SALA": "GER ADM",
      "EMAIL": "confecção@grupodass.com.br"
    },
    {
      "PATRIMONIO": "157623",
      "EQUIPAMENTO": "AR CONDICIONADO",
      "NOME": "AR CONDICIONADO",
      "MODELO": "SPLIT",
      "TIPO": "INVERTER",
      "MARCA": "ADMRAL",
      "RESPONSAVEL": "",
      "TENSAO": "220 V",
      "FLUIDO": "R410A",
      "BTUS": "18K BTUS",
      "SETOR": "ADMINISTRATIVO",
      "SALA": "T.I. INFRA",
      "EMAIL": "confecção@grupodass.com.br"
    },
    {
      "PATRIMONIO": "157656",
      "EQUIPAMENTO": "AR CONDICIONADO",
      "NOME": "AR CONDICIONADO",
      "MODELO": "SPLIT",
      "TIPO": "INVERTER",
      "MARCA": "-",
      "RESPONSAVEL": "",
      "TENSAO": "220 V",
      "FLUIDO": "-",
      "BTUS": "18K BTUS",
      "SETOR": "ADMINISTRATIVO",
      "SALA": "MELHORIA",
      "EMAIL": "confecção@grupodass.com.br"
    },
    {
      "PATRIMONIO": "103999",
      "EQUIPAMENTO": "AR CONDICIONADO",
      "NOME": "AR CONDICIONADO",
      "MODELO": "SPLIT",
      "TIPO": "INVERTER",
      "MARCA": "ELGIN",
      "RESPONSAVEL": "",
      "TENSAO": "220",
      "FLUIDO": "R410A",
      "BTUS": "24K BTUS",
      "SETOR": "SALA IMPRESSÃO",
      "SALA": "SALA IMPRESSÃO UMBRO",
      "EMAIL": "confecção@grupodass.com.br"
    },
    {
      "PATRIMONIO": "72956",
      "EQUIPAMENTO": "AR CONDICIONADO",
      "NOME": "AR CONDICIONADO",
      "MODELO": "SPLIT",
      "TIPO": "INVERTER",
      "MARCA": "LG",
      "RESPONSAVEL": "",
      "TENSAO": "220V",
      "FLUIDO": "R410A",
      "BTUS": "22K BTUS",
      "SETOR": "BISTRÔ",
      "SALA": "BISTRÔ",
      "EMAIL": "confecção@grupodass.com.br"
    },
    {
      "PATRIMONIO": "115471",
      "EQUIPAMENTO": "AR CONDICIONADO",
      "NOME": "AR CONDICIONADO",
      "MODELO": "SPLIT",
      "TIPO": "INVERTER",
      "MARCA": "ELGIN",
      "RESPONSAVEL": "",
      "TENSAO": "220V",
      "FLUIDO": "R410A",
      "BTUS": "24K BTUS",
      "SETOR": "COZINHA DEPOSITO",
      "SALA": "COZINHA DEPOSITO",
      "EMAIL": "confecção@grupodass.com.br"
    },
    {
      "PATRIMONIO": "6741",
      "EQUIPAMENTO": "AR CONDICIONADO",
      "NOME": "AR CONDICIONADO",
      "MODELO": "SPLIT",
      "TIPO": "CONVENCIONAL",
      "MARCA": "GREE",
      "RESPONSAVEL": "",
      "TENSAO": "220V",
      "FLUIDO": "R22",
      "BTUS": "18K BTUS",
      "SETOR": "ADMINISTRAÇÃO",
      "SALA": "COMPETÊNCIA",
      "EMAIL": "confecção@grupodass.com.br"
    },
    {
      "PATRIMONIO": "115472",
      "EQUIPAMENTO": "AR CONDICIONADO",
      "NOME": "AR CONDICIONADO",
      "MODELO": "SPLIT",
      "TIPO": "INVERTER",
      "MARCA": "ELGIN",
      "RESPONSAVEL": "",
      "TENSAO": "220 V",
      "FLUIDO": "R410A",
      "BTUS": "24K BTUS",
      "SETOR": "COZINHA",
      "SALA": "DEPOSITO",
      "EMAIL": "confecção@grupodass.com.br"
    },
    {
      "PATRIMONIO": "87609",
      "EQUIPAMENTO": "AR CONDICIONADO",
      "NOME": "AR CONDICIONADO",
      "MODELO": "PISO TETO",
      "TIPO": "INVERTER",
      "MARCA": "LG",
      "RESPONSAVEL": "",
      "TENSAO": "220 V",
      "FLUIDO": "R410A",
      "BTUS": "36K BTUS",
      "SETOR": "ADM",
      "SALA": "QUALIDADE",
      "EMAIL": "confecção@grupodass.com.br"
    },
    {
      "PATRIMONIO": "87608",
      "EQUIPAMENTO": "AR CONDICIONADO",
      "NOME": "AR CONDICIONADO",
      "MODELO": "SPLIT",
      "TIPO": "INVERTER",
      "MARCA": "LG",
      "RESPONSAVEL": "",
      "TENSAO": "220V",
      "FLUIDO": "R410",
      "BTUS": "22K BTUS",
      "SETOR": "GERENCIA",
      "SALA": "SUPERAÇÃO SSMA",
      "EMAIL": "confecção@grupodass.com.br"
    },
    {
      "PATRIMONIO": "103801",
      "EQUIPAMENTO": "AR CONDICIONADO",
      "NOME": "AR CONDICIONADO",
      "MODELO": "K7",
      "TIPO": "CONVENCIONAL",
      "MARCA": "ELGIN",
      "RESPONSAVEL": "",
      "TENSAO": "220 V",
      "FLUIDO": "R410",
      "BTUS": "60K BTUS",
      "SETOR": "IMPRESSÃO DIGITAL",
      "SALA": "IMPRESSÃO DIGITAL",
      "EMAIL": "confecção@grupodass.com.br"
    },
    {
      "PATRIMONIO": "87607",
      "EQUIPAMENTO": "AR CONDICIONADO",
      "NOME": "AR CONDICIONADO",
      "MODELO": "SPLIT",
      "TIPO": "INVERTER",
      "MARCA": "LG",
      "RESPONSAVEL": "",
      "TENSAO": "220 V",
      "FLUIDO": "R410a",
      "BTUS": "22K BTUS",
      "SETOR": "GER",
      "SALA": "PAIXÃO",
      "EMAIL": "confecção@grupodass.com.br"
    },
    {
      "PATRIMONIO": "41054",
      "EQUIPAMENTO": "AR CONDICIONADO",
      "NOME": "AR CONDICIONADO",
      "MODELO": "",
      "TIPO": "CONVENCIONAL",
      "MARCA": "ELECTROLUX",
      "RESPONSAVEL": "",
      "TENSAO": "220V",
      "FLUIDO": "R22",
      "BTUS": "18K BTUS",
      "SETOR": "EXPEDIÇÃO",
      "SALA": "EXPEDIÇÃO",
      "EMAIL": "confecção@grupodass.com.br"
    },
    {
      "PATRIMONIO": "6418",
      "EQUIPAMENTO": "AR CONDICIONADO",
      "NOME": "AR CONDICIONADO",
      "MODELO": "",
      "TIPO": "CONVENCIONAL",
      "MARCA": "LG",
      "RESPONSAVEL": "",
      "TENSAO": "220V",
      "FLUIDO": "R22",
      "BTUS": "18K BTUS",
      "SETOR": "EXPEDIÇÃO",
      "SALA": "EXP COORDENAÇÃO PRIVATE",
      "EMAIL": "confecção@grupodass.com.br"
    },
    {
      "PATRIMONIO": "41055",
      "EQUIPAMENTO": "AR CONDICIONADO",
      "NOME": "AR CONDICIONADO",
      "MODELO": "",
      "TIPO": "CONVENCIONAL",
      "MARCA": "GREE",
      "RESPONSAVEL": "",
      "TENSAO": "220 V",
      "FLUIDO": "R22",
      "BTUS": "7K BTUS",
      "SETOR": "EXPEDIÇÃO GERÊNCIA",
      "SALA": "EXPEDIÇÃO GERÊNCIA",
      "EMAIL": "confecção@grupodass.com.br"
    },
    {
      "PATRIMONIO": "92288",
      "EQUIPAMENTO": "AR CONDICIONADO",
      "NOME": "AR CONDICIONADO",
      "MODELO": "",
      "TIPO": "INVERTER",
      "MARCA": "LG",
      "RESPONSAVEL": "",
      "TENSAO": "220V",
      "FLUIDO": "R410A",
      "BTUS": "18K BTUS",
      "SETOR": "T.I.",
      "SALA": "T.I. INFRA",
      "EMAIL": "confecção@grupodass.com.br"
    },
    {
      "PATRIMONIO": "103800",
      "EQUIPAMENTO": "AR CONDICIONADO",
      "NOME": "AR CONDICIONADO",
      "MODELO": "K7",
      "TIPO": "CONVENCIONAL",
      "MARCA": "ELGIN",
      "RESPONSAVEL": "",
      "TENSAO": "220V",
      "FLUIDO": "R410A",
      "BTUS": "60K BTUS",
      "SETOR": "IMPRESSÃO DIGITAL",
      "SALA": "IMPRESSÃO DIGITAL",
      "EMAIL": "confecção@grupodass.com.br"
    },
    {
      "PATRIMONIO": "103802",
      "EQUIPAMENTO": "AR CONDICIONADO",
      "NOME": "AR CONDICIONADO",
      "MODELO": "K7",
      "TIPO": "CONVENCIONAL",
      "MARCA": "ELGIN",
      "RESPONSAVEL": "",
      "TENSAO": "220V",
      "FLUIDO": "R410A",
      "BTUS": "60K BTUS",
      "SETOR": "IMPRESSÃO DIGITAL",
      "SALA": "IMPRESSÃO DIGITAL",
      "EMAIL": "confecção@grupodass.com.br"
    },
    {
      "PATRIMONIO": "103805",
      "EQUIPAMENTO": "AR CONDICIONADO",
      "NOME": "AR CONDICIONADO",
      "MODELO": "K7",
      "TIPO": "CONVENCIONAL",
      "MARCA": "ELGIN",
      "RESPONSAVEL": "",
      "TENSAO": "220 V",
      "FLUIDO": "R410",
      "BTUS": "60K BTUS",
      "SETOR": "IMPRESSÃO DIGITAL",
      "SALA": "IMPRESSÃO DIGITAL",
      "EMAIL": "confecção@grupodass.com.br"
    },
    {
      "PATRIMONIO": "103807",
      "EQUIPAMENTO": "AR CONDICIONADO",
      "NOME": "AR CONDICIONADO",
      "MODELO": "K7",
      "TIPO": "CONVENCIONAL",
      "MARCA": "ELGIN",
      "RESPONSAVEL": "",
      "TENSAO": "220 V",
      "FLUIDO": "R410",
      "BTUS": "60K BTUS",
      "SETOR": "IMPRESSÃO DIGITAL",
      "SALA": "IMPRESSÃO DIGITAL",
      "EMAIL": "confecção@grupodass.com.br"
    },
    {
      "PATRIMONIO": "103809",
      "EQUIPAMENTO": "AR CONDICIONADO",
      "NOME": "AR CONDICIONADO",
      "MODELO": "K7",
      "TIPO": "CONVENCIONAL",
      "MARCA": "ELGIN",
      "RESPONSAVEL": "",
      "TENSAO": "220 V",
      "FLUIDO": "R410",
      "BTUS": "60K BTUS",
      "SETOR": "IMPRESSÃO DIGITAL",
      "SALA": "IMPRESSÃO DIGITAL",
      "EMAIL": "confecção@grupodass.com.br"
    },
    {
      "PATRIMONIO": "100157",
      "EQUIPAMENTO": "AR CONDICIONADO",
      "NOME": "AR CONDICIONADO",
      "MODELO": "K7",
      "TIPO": "CONVENCIONAL",
      "MARCA": "ELGIN",
      "RESPONSAVEL": "",
      "TENSAO": "220 V",
      "FLUIDO": "R410",
      "BTUS": "48K BTUS",
      "SETOR": "GER",
      "SALA": "RESPEITO",
      "EMAIL": "confecção@grupodass.com.br"
    },
    {
      "PATRIMONIO": "100158",
      "EQUIPAMENTO": "AR CONDICIONADO",
      "NOME": "AR CONDICIONADO",
      "MODELO": "K7",
      "TIPO": "CONVENCIONAL",
      "MARCA": "ELGIN",
      "RESPONSAVEL": "",
      "TENSAO": "220 V",
      "FLUIDO": "R410",
      "BTUS": "48K BTUS",
      "SETOR": "GER",
      "SALA": "RESPEITO",
      "EMAIL": "confecção@grupodass.com.br"
    },
    {
      "PATRIMONIO": "100159",
      "EQUIPAMENTO": "AR CONDICIONADO",
      "NOME": "AR CONDICIONADO",
      "MODELO": "K7",
      "TIPO": "CONVENCIONAL",
      "MARCA": "ELGIN",
      "RESPONSAVEL": "",
      "TENSAO": "220 V",
      "FLUIDO": "R410",
      "BTUS": "48K BTUS",
      "SETOR": "GER",
      "SALA": "RESPEITO",
      "EMAIL": "confecção@grupodass.com.br"
    },
    {
      "PATRIMONIO": "93414",
      "EQUIPAMENTO": "AR CONDICIONADO",
      "NOME": "AR CONDICIONADO",
      "MODELO": "PISO TETO",
      "TIPO": "INVERTER",
      "MARCA": "ELGIN",
      "RESPONSAVEL": "",
      "TENSAO": "220 V",
      "FLUIDO": "R410",
      "BTUS": "80K BTUS",
      "SETOR": "GER",
      "SALA": "DESENVOLVIMENTO",
      "EMAIL": "confecção@grupodass.com.br"
    },
    {
      "PATRIMONIO": "92479",
      "EQUIPAMENTO": "AR CONDICIONADO",
      "NOME": "AR CONDICIONADO",
      "MODELO": "PISO TETO",
      "TIPO": "CONVENCIONAL",
      "MARCA": "ELGIN",
      "RESPONSAVEL": "",
      "TENSAO": "220V",
      "FLUIDO": "R410",
      "BTUS": "80K BTUS",
      "SETOR": "GER",
      "SALA": "PPCP",
      "EMAIL": "confecção@grupodass.com.br"
    },
    {
      "PATRIMONIO": "144252",
      "EQUIPAMENTO": "AR CONDICIONADO",
      "NOME": "AR CONDICIONADO",
      "MODELO": "SPLIT",
      "TIPO": "INVERTER",
      "MARCA": "LG",
      "RESPONSAVEL": "",
      "TENSAO": "220V",
      "FLUIDO": "R410",
      "BTUS": "18K BTUS",
      "SETOR": "GER",
      "SALA": "INTEGRIDADE",
      "EMAIL": "confecção@grupodass.com.br"
    },
    {
      "PATRIMONIO": "117562",
      "EQUIPAMENTO": "AR CONDICIONADO",
      "NOME": "AR CONDICIONADO",
      "MODELO": "SPLIT",
      "TIPO": "INVERTER",
      "MARCA": "ELGIN",
      "RESPONSAVEL": "",
      "TENSAO": "220V",
      "FLUIDO": "R410A",
      "BTUS": "24K BTUS",
      "SETOR": "ADMINISTRATIVO",
      "SALA": "GER INDUSTRIAL",
      "EMAIL": "confecção@grupodass.com.br"
    },
    {
      "PATRIMONIO": "87604",
      "EQUIPAMENTO": "AR CONDICIONADO",
      "NOME": "AR CONDICIONADO",
      "MODELO": "SPLIT",
      "TIPO": "INVERTER",
      "MARCA": "LG",
      "RESPONSAVEL": "",
      "TENSAO": "220V",
      "FLUIDO": "R410A",
      "BTUS": "11.5K BTUS",
      "SETOR": "GER",
      "SALA": "GER OPER COOSTURA",
      "EMAIL": "confecção@grupodass.com.br"
    },
    {
      "PATRIMONIO": "87602",
      "EQUIPAMENTO": "AR CONDICIONADO",
      "NOME": "AR CONDICIONADO",
      "MODELO": "SPLIT",
      "TIPO": "INVERTER",
      "MARCA": "LG",
      "RESPONSAVEL": "",
      "TENSAO": "220 V",
      "FLUIDO": "R410A",
      "BTUS": "18K BTUS",
      "SETOR": "INTEGRIDADE",
      "SALA": "INTEGRIDADE",
      "EMAIL": "confecção@grupodass.com.br"
    },
    {
      "PATRIMONIO": "115396",
      "EQUIPAMENTO": "AR CONDICIONADO",
      "NOME": "AR CONDICIONADO",
      "MODELO": "SPLIT",
      "TIPO": "INVERTER",
      "MARCA": "ELGIN",
      "RESPONSAVEL": "",
      "TENSAO": "220 V",
      "FLUIDO": "R410A",
      "BTUS": "12K BTUS",
      "SETOR": "GER",
      "SALA": "GER OCUP EMBELEZAMENTO",
      "EMAIL": "confecção@grupodass.com.br"
    },
    {
      "PATRIMONIO": "100168",
      "EQUIPAMENTO": "AR CONDICIONADO",
      "NOME": "AR CONDICIONADO",
      "MODELO": "SPLIT",
      "TIPO": "INVERTER",
      "MARCA": "SAMSUNG",
      "RESPONSAVEL": "",
      "TENSAO": "220V",
      "FLUIDO": "R410",
      "BTUS": "9K BTUS",
      "SETOR": "ADMINISTRATIVO",
      "SALA": "COMPROMISSO",
      "EMAIL": "confecção@grupodass.com.br"
    },
    {
      "PATRIMONIO": "87605",
      "EQUIPAMENTO": "AR CONDICIONADO",
      "NOME": "AR CONDICIONADO",
      "MODELO": "SPLIT",
      "TIPO": "INVERTER",
      "MARCA": "LG",
      "RESPONSAVEL": "",
      "TENSAO": "220V",
      "FLUIDO": "R410A",
      "BTUS": "11.5K BTUS",
      "SETOR": "",
      "SALA": "SALA TINTAS",
      "EMAIL": "confecção@grupodass.com.br"
    },
    {
      "PATRIMONIO": "100169",
      "EQUIPAMENTO": "AR CONDICIONADO",
      "NOME": "AR CONDICIONADO",
      "MODELO": "SPLIT",
      "TIPO": "INVERTER",
      "MARCA": "SAMSUNG",
      "RESPONSAVEL": "",
      "TENSAO": "220 V",
      "FLUIDO": "R410",
      "BTUS": "9K BTUS",
      "SETOR": "MANUTENÇÃO",
      "SALA": "APOIO EMBELEZAMENTO",
      "EMAIL": "confecção@grupodass.com.br"
    },
    {
      "PATRIMONIO": "105438",
      "EQUIPAMENTO": "AR CONDICIONADO",
      "NOME": "AR CONDICIONADO",
      "MODELO": "SPLIT",
      "TIPO": "INVERTER",
      "MARCA": "ELGIN",
      "RESPONSAVEL": "",
      "TENSAO": "220 V",
      "FLUIDO": "R410",
      "BTUS": "24K BTUS",
      "SETOR": "3 TREINAMENTO PAV.1",
      "SALA": "3 TREINAMENTO PAV.1",
      "EMAIL": "confecção@grupodass.com.br"
    },
    {
      "PATRIMONIO": "41053",
      "EQUIPAMENTO": "AR CONDICIONADO",
      "NOME": "AR CONDICIONADO",
      "MODELO": "SPLIT",
      "TIPO": "CONVENCIONAL",
      "MARCA": "ELECTROLUX",
      "RESPONSAVEL": "",
      "TENSAO": "220 V",
      "FLUIDO": "R22",
      "BTUS": "18K BTUS",
      "SETOR": "MANUTENÇÃO T.I.",
      "SALA": "MANUTENÇÃO T.I.",
      "EMAIL": "confecção@grupodass.com.br"
    },
    {
      "PATRIMONIO": "103998",
      "EQUIPAMENTO": "AR CONDICIONADO",
      "NOME": "AR CONDICIONADO",
      "MODELO": "SPLIT",
      "TIPO": "INVERTER",
      "MARCA": "ELGIN",
      "RESPONSAVEL": "",
      "TENSAO": "220 V",
      "FLUIDO": "R410",
      "BTUS": "24K BTUS",
      "SETOR": "MANUTENÇÃO",
      "SALA": "MANUTENÇÃO",
      "EMAIL": "confecção@grupodass.com.br"
    },
    {
      "PATRIMONIO": "117558",
      "EQUIPAMENTO": "AR CONDICIONADO",
      "NOME": "AR CONDICIONADO",
      "MODELO": "SPLIT",
      "TIPO": "INVERTER",
      "MARCA": "ELGIN",
      "RESPONSAVEL": "",
      "TENSAO": "220 V",
      "FLUIDO": "R410",
      "BTUS": "24K BTUS",
      "SETOR": "ADMINISTRATIVO",
      "SALA": "SSMA",
      "EMAIL": "confecção@grupodass.com.br"
    },
    {
      "PATRIMONIO": "70933",
      "EQUIPAMENTO": "AR CONDICIONADO",
      "NOME": "AR CONDICIONADO",
      "MODELO": "PISO TETO",
      "TIPO": "CONVENCIONAL",
      "MARCA": "LG",
      "RESPONSAVEL": "",
      "TENSAO": "220 V",
      "FLUIDO": "R22",
      "BTUS": "24K BTUS",
      "SETOR": "MANUTENÇÃO",
      "SALA": "TREINAMENTO 04",
      "EMAIL": "confecção@grupodass.com.br"
    },
    {
      "PATRIMONIO": "111053",
      "EQUIPAMENTO": "AR CONDICIONADO",
      "NOME": "AR CONDICIONADO",
      "MODELO": "SPLIT",
      "TIPO": "INVERTER",
      "MARCA": "ELGIN",
      "RESPONSAVEL": "",
      "TENSAO": "220 V",
      "FLUIDO": "R410",
      "BTUS": "30K BTUS",
      "SETOR": "TINTAS E TELAS",
      "SALA": "FOTOLITO",
      "EMAIL": "confecção@grupodass.com.br"
    },
    {
      "PATRIMONIO": "105437",
      "EQUIPAMENTO": "AR CONDICIONADO",
      "NOME": "AR CONDICIONADO",
      "MODELO": "SPLIT",
      "TIPO": "INVERTER",
      "MARCA": "ELGIN",
      "RESPONSAVEL": "",
      "TENSAO": "220 V",
      "FLUIDO": "R410",
      "BTUS": "24K BTUS",
      "SETOR": "PAV.1 COSTURA",
      "SALA": "1 TREINAMENTO PAV.1",
      "EMAIL": "confecção@grupodass.com.br"
    },
    {
      "PATRIMONIO": "72991",
      "EQUIPAMENTO": "AR CONDICIONADO",
      "NOME": "AR CONDICIONADO",
      "MODELO": "SPLIT",
      "TIPO": "INVERTER",
      "MARCA": "LG",
      "RESPONSAVEL": "",
      "TENSAO": "220 V",
      "FLUIDO": "R410",
      "BTUS": "22K BTUS",
      "SETOR": "LABORATÓRIO",
      "SALA": "REUNIÃO LABORATÓRIO",
      "EMAIL": "confecção@grupodass.com.br"
    },
    {
      "PATRIMONIO": "105439",
      "EQUIPAMENTO": "AR CONDICIONADO",
      "NOME": "AR CONDICIONADO",
      "MODELO": "SPLIT",
      "TIPO": "INVERTER",
      "MARCA": "ELGIN",
      "RESPONSAVEL": "",
      "TENSAO": "220 V",
      "FLUIDO": "R410",
      "BTUS": "24K BTUS",
      "SETOR": "COSTURA",
      "SALA": "SL 2 TREINAMENTO PAV.1",
      "EMAIL": "confecção@grupodass.com.br"
    },
    {
      "PATRIMONIO": "125035",
      "EQUIPAMENTO": "AR CONDICIONADO",
      "NOME": "AR CONDICIONADO",
      "MODELO": "K7",
      "TIPO": "",
      "MARCA": "ELGIN",
      "RESPONSAVEL": "",
      "TENSAO": "220 V",
      "FLUIDO": "",
      "BTUS": "48K BTUS",
      "SETOR": "GER",
      "SALA": "INDICADORES",
      "EMAIL": "confecção@grupodass.com.br"
    },
    {
      "PATRIMONIO": "125036",
      "EQUIPAMENTO": "AR CONDICIONADO",
      "NOME": "AR CONDICIONADO",
      "MODELO": "",
      "TIPO": "",
      "MARCA": "ELGIN",
      "RESPONSAVEL": "",
      "TENSAO": "220 V",
      "FLUIDO": "",
      "BTUS": "48K BTUS",
      "SETOR": "GER",
      "SALA": "INDICADORES",
      "EMAIL": "confecção@grupodass.com.br"
    },
    {
      "PATRIMONIO": "122666",
      "EQUIPAMENTO": "AR CONDICIONADO",
      "NOME": "AR CONDICIONADO",
      "MODELO": "",
      "TIPO": "",
      "MARCA": "ELGIN",
      "RESPONSAVEL": "",
      "TENSAO": "220 V",
      "FLUIDO": "",
      "BTUS": "48K BTUS",
      "SETOR": "GER",
      "SALA": "TEMPOS E METODOS",
      "EMAIL": "confecção@grupodass.com.br"
    },
    {
      "PATRIMONIO": "125037",
      "EQUIPAMENTO": "AR CONDICIONADO",
      "NOME": "AR CONDICIONADO",
      "MODELO": "",
      "TIPO": "",
      "MARCA": "ELGIN",
      "RESPONSAVEL": "",
      "TENSAO": "220 V",
      "FLUIDO": "",
      "BTUS": "12K BTUS",
      "SETOR": "CORTE",
      "SALA": "CAT",
      "EMAIL": "confecção@grupodass.com.br"
    },
    {
      "PATRIMONIO": "128167",
      "EQUIPAMENTO": "AR CONDICIONADO",
      "NOME": "AR CONDICIONADO",
      "MODELO": "",
      "TIPO": "",
      "MARCA": "ELGIN",
      "RESPONSAVEL": "",
      "TENSAO": "220 V",
      "FLUIDO": "",
      "BTUS": "60K BTUS",
      "SETOR": "CORTE",
      "SALA": "REUNIÃO",
      "EMAIL": "confecção@grupodass.com.br"
    },
    {
      "PATRIMONIO": "128212",
      "EQUIPAMENTO": "AR CONDICIONADO",
      "NOME": "AR CONDICIONADO",
      "MODELO": "",
      "TIPO": "",
      "MARCA": "ELGIN",
      "RESPONSAVEL": "",
      "TENSAO": "220 V",
      "FLUIDO": "",
      "BTUS": "24K BTUS",
      "SETOR": "CORTE",
      "SALA": "ADM ALMX",
      "EMAIL": "confecção@grupodass.com.br"
    },
    {
      "PATRIMONIO": "128211",
      "EQUIPAMENTO": "AR CONDICIONADO",
      "NOME": "AR CONDICIONADO",
      "MODELO": "",
      "TIPO": "",
      "MARCA": "",
      "RESPONSAVEL": "",
      "TENSAO": "220 V",
      "FLUIDO": "",
      "BTUS": "18K BTUS",
      "SETOR": "CORTE",
      "SALA": "SALA FISCAL",
      "EMAIL": "confecção@grupodass.com.br"
    },
    {
      "PATRIMONIO": "125251",
      "EQUIPAMENTO": "AR CONDICIONADO",
      "NOME": "AR CONDICIONADO",
      "MODELO": "k7",
      "TIPO": "CONVEN",
      "MARCA": "ELGIN",
      "RESPONSAVEL": "",
      "TENSAO": "220 V",
      "FLUIDO": "A410A",
      "BTUS": "48K BTUS",
      "SETOR": "",
      "SALA": "LABORATORIO",
      "EMAIL": "confecção@grupodass.com.br"
    },
    {
      "PATRIMONIO": "125260",
      "EQUIPAMENTO": "AR CONDICIONADO",
      "NOME": "AR CONDICIONADO",
      "MODELO": "PISO TETO",
      "TIPO": "CONVEN",
      "MARCA": "ELGIN",
      "RESPONSAVEL": "",
      "TENSAO": "220 V",
      "FLUIDO": "380V",
      "BTUS": "60K BTUS",
      "SETOR": "",
      "SALA": "SALA CLIMATIZADA LAB",
      "EMAIL": "confecção@grupodass.com.br"
    },
    {
      "PATRIMONIO": "125259",
      "EQUIPAMENTO": "AR CONDICIONADO",
      "NOME": "AR CONDICIONADO",
      "MODELO": "PISO TETO",
      "TIPO": "CONVEN",
      "MARCA": "ALGIN",
      "RESPONSAVEL": "",
      "TENSAO": "220 V",
      "FLUIDO": "380V",
      "BTUS": "60K BTUS",
      "SETOR": "MAN",
      "SALA": "PROTOTIPO",
      "EMAIL": "confecção@grupodass.com.br"
    },
    {
      "PATRIMONIO": "128210",
      "EQUIPAMENTO": "AR CONDICIONADO",
      "NOME": "AR CONDICIONADO",
      "MODELO": "SPLIT",
      "TIPO": "CONVENCIONAL",
      "MARCA": "ELGIN",
      "RESPONSAVEL": "",
      "TENSAO": "220 V",
      "FLUIDO": "380V",
      "BTUS": "48K BTUS",
      "SETOR": "CORTE",
      "SALA": "TREINAMENTO GER",
      "EMAIL": "confecção@grupodass.com.br"
    },
    {
      "PATRIMONIO": "137451",
      "EQUIPAMENTO": "AR CONDICIONADO",
      "NOME": "AR CONDICIONADO",
      "MODELO": "SPLIT",
      "TIPO": "CONVENCIONAL",
      "MARCA": "ELGIN",
      "RESPONSAVEL": "",
      "TENSAO": "220 V",
      "FLUIDO": "R410",
      "BTUS": "18K BTUS",
      "SETOR": "SALA IMPRESSÃO",
      "SALA": "SALA IMPRESSÃO",
      "EMAIL": "confecção@grupodass.com.br"
    },
    {
      "PATRIMONIO": "137450",
      "EQUIPAMENTO": "AR CONDICIONADO",
      "NOME": "AR CONDICIONADO",
      "MODELO": "SPLIT",
      "TIPO": "INVERTER",
      "MARCA": "ELGIN",
      "RESPONSAVEL": "",
      "TENSAO": "220 V",
      "FLUIDO": "R410a",
      "BTUS": "18K BTUS",
      "SETOR": "SALA IMPRESSÃO",
      "SALA": "SALA IMPRESSÃO",
      "EMAIL": "confecção@grupodass.com.br"
    },
    {
      "PATRIMONIO": "143429",
      "EQUIPAMENTO": "AR CONDICIONADO",
      "NOME": "AR CONDICIONADO",
      "MODELO": "SPLIT",
      "TIPO": "CONVENCIONAL",
      "MARCA": "ELGIN",
      "RESPONSAVEL": "",
      "TENSAO": "220 V",
      "FLUIDO": "R410A",
      "BTUS": "9K BTUS",
      "SETOR": "COZINHA",
      "SALA": "SALA NUTRICIONISTA",
      "EMAIL": "confecção@grupodass.com.br"
    },
    {
      "PATRIMONIO": "143430",
      "EQUIPAMENTO": "AR CONDICIONADO",
      "NOME": "AR CONDICIONADO",
      "MODELO": "K7",
      "TIPO": "CONVENCIONAL",
      "MARCA": "ELGIN",
      "RESPONSAVEL": "",
      "TENSAO": "220 V",
      "FLUIDO": "R410",
      "BTUS": "60K BTUS",
      "SETOR": "ALM",
      "SALA": "ALM",
      "EMAIL": "confecção@grupodass.com.br"
    },
    {
      "PATRIMONIO": "143431",
      "EQUIPAMENTO": "AR CONDICIONADO",
      "NOME": "AR CONDICIONADO",
      "MODELO": "SPLIT",
      "TIPO": "CONVENCIONAL",
      "MARCA": "TCL",
      "RESPONSAVEL": "",
      "TENSAO": "220 V",
      "FLUIDO": "R410A",
      "BTUS": "12K BTUS",
      "SETOR": "",
      "SALA": "TI INFRA",
      "EMAIL": "confecção@grupodass.com.br"
    },
    {
      "PATRIMONIO": "103804",
      "EQUIPAMENTO": "AR CONDICIONADO",
      "NOME": "AR CONDICIONADO",
      "MODELO": "K7",
      "TIPO": "CONVENCIONAL",
      "MARCA": "ELGIN",
      "RESPONSAVEL": "",
      "TENSAO": "220 V",
      "FLUIDO": "R410",
      "BTUS": "60K BTUS",
      "SETOR": "IMPRESSÃO DIGITAL",
      "SALA": "IMPRESSÃO DIGITAL",
      "EMAIL": "confecção@grupodass.com.br"
    },
    {
      "PATRIMONIO": "144182",
      "EQUIPAMENTO": "AR CONDICIONADO",
      "NOME": "AR CONDICIONADO",
      "MODELO": "EPLIT",
      "TIPO": "INVERTER",
      "MARCA": "ELGIN",
      "RESPONSAVEL": "",
      "TENSAO": "220 V",
      "FLUIDO": "R140A",
      "BTUS": "12K BTUS",
      "SETOR": "ERGONOMMIA",
      "SALA": "ERGONOMMIA",
      "EMAIL": "confecção@grupodass.com.br"
    },
    {
      "PATRIMONIO": "115398",
      "EQUIPAMENTO": "CORTINA DE AR",
      "NOME": "CORTINA DE AR",
      "MODELO": "CORTINA DE AR",
      "TIPO": "90CM",
      "MARCA": "VIX",
      "RESPONSAVEL": "",
      "TENSAO": "220V",
      "FLUIDO": "NÃO SE APLICA",
      "BTUS": "NÃO SE APLICA",
      "SETOR": "SETOR TINTAS",
      "SALA": "SETOR TINTAS",
      "EMAIL": "confecção@grupodass.com.br"
    },
    {
      "PATRIMONIO": "116573",
      "EQUIPAMENTO": "CORTINA DE AR",
      "NOME": "CORTINA DE AR",
      "MODELO": "CORTINA DE AR",
      "TIPO": "1,20M",
      "MARCA": "DUGOLD",
      "RESPONSAVEL": "",
      "TENSAO": "220V",
      "FLUIDO": "NÃO SE APLICA",
      "BTUS": "NÃO SE APLICA",
      "SETOR": "COZINHA",
      "SALA": "COZINHA",
      "EMAIL": "confecção@grupodass.com.br"
    },
    {
      "PATRIMONIO": "116577",
      "EQUIPAMENTO": "CORTINA DE AR",
      "NOME": "CORTINA DE AR",
      "MODELO": "CORTINA DE AR",
      "TIPO": "1M",
      "MARCA": "DUGOLD",
      "RESPONSAVEL": "",
      "TENSAO": "220V",
      "FLUIDO": "NÃO SE APLICA",
      "BTUS": "NÃO SE APLICA",
      "SETOR": "COZINHA",
      "SALA": "COZINHA",
      "EMAIL": "confecção@grupodass.com.br"
    },
    {
      "PATRIMONIO": "116575",
      "EQUIPAMENTO": "CORTINA DE AR",
      "NOME": "CORTINA DE AR",
      "MODELO": "CORTINA DE AR",
      "TIPO": "1M",
      "MARCA": "DUGOLD",
      "RESPONSAVEL": "",
      "TENSAO": "220 V",
      "FLUIDO": "NÃO SE APLICA",
      "BTUS": "NÃO SE APLICA",
      "SETOR": "COZINHA",
      "SALA": "COZINHA",
      "EMAIL": "confecção@grupodass.com.br"
    },
    {
      "PATRIMONIO": "116571",
      "EQUIPAMENTO": "CORTINA DE AR",
      "NOME": "CORTINA DE AR",
      "MODELO": "CORTINA DE AR",
      "TIPO": "90CM",
      "MARCA": "DUGOLD",
      "RESPONSAVEL": "",
      "TENSAO": "220 V",
      "FLUIDO": "NÃO SE APLICA",
      "BTUS": "NÃO SE APLICA",
      "SETOR": "COZINHA",
      "SALA": "COZINHA",
      "EMAIL": "confecção@grupodass.com.br"
    },
    {
      "PATRIMONIO": "116570",
      "EQUIPAMENTO": "CORTINA DE AR",
      "NOME": "CORTINA DE AR",
      "MODELO": "CORTINA DE AR",
      "TIPO": "1,20M",
      "MARCA": "DUGOLD",
      "RESPONSAVEL": "",
      "TENSAO": "220 V",
      "FLUIDO": "NÃO SE APLICA",
      "BTUS": "NÃO SE APLICA",
      "SETOR": "COZINHA",
      "SALA": "COZINHA",
      "EMAIL": "confecção@grupodass.com.br"
    },
    {
      "PATRIMONIO": "116576",
      "EQUIPAMENTO": "CORTINA DE AR",
      "NOME": "CORTINA DE AR",
      "MODELO": "CORTINA DE AR",
      "TIPO": "90CM",
      "MARCA": "DUGOLD",
      "RESPONSAVEL": "",
      "TENSAO": "220 V",
      "FLUIDO": "NÃO SE APLICA",
      "BTUS": "NÃO SE APLICA",
      "SETOR": "COZINHA",
      "SALA": "COZINHA",
      "EMAIL": "confecção@grupodass.com.br"
    },
    {
      "PATRIMONIO": "116569",
      "EQUIPAMENTO": "CORTINA DE AR",
      "NOME": "CORTINA DE AR",
      "MODELO": "CORTINA DE AR",
      "TIPO": "1M",
      "MARCA": "DUGOLD",
      "RESPONSAVEL": "",
      "TENSAO": "220 V",
      "FLUIDO": "NÃO SE APLICA",
      "BTUS": "NÃO SE APLICA",
      "SETOR": "COZINHA",
      "SALA": "COZINHA",
      "EMAIL": "confecção@grupodass.com.br"
    },
    {
      "PATRIMONIO": "116574",
      "EQUIPAMENTO": "CORTINA DE AR",
      "NOME": "CORTINA DE AR",
      "MODELO": "CORTINA DE AR",
      "TIPO": "1,20M",
      "MARCA": "DUGOLD",
      "RESPONSAVEL": "",
      "TENSAO": "220 V",
      "FLUIDO": "NÃO SE APLICA",
      "BTUS": "NÃO SE APLICA",
      "SETOR": "COZINHA",
      "SALA": "COZINHA",
      "EMAIL": "confecção@grupodass.com.br"
    },
    {
      "PATRIMONIO": "116572",
      "EQUIPAMENTO": "CORTINA DE AR",
      "NOME": "CORTINA DE AR",
      "MODELO": "CORTINA DE AR",
      "TIPO": "1,20M",
      "MARCA": "DUGOLD",
      "RESPONSAVEL": "",
      "TENSAO": "220V",
      "FLUIDO": "NÃO SE APLICA",
      "BTUS": "NÃO SE APLICA",
      "SETOR": "COZINHA",
      "SALA": "COZINHA",
      "EMAIL": "confecção@grupodass.com.br"
    },
    {
      "PATRIMONIO": "115397",
      "EQUIPAMENTO": "CORTINA DE AR",
      "NOME": "CORTINA DE AR",
      "MODELO": "CORTINA DE AR",
      "TIPO": "90CM",
      "MARCA": "VIX",
      "RESPONSAVEL": "",
      "TENSAO": "220 V",
      "FLUIDO": "NÃO SE APLICA",
      "BTUS": "NÃO SE APLICA",
      "SETOR": "COZINHA",
      "SALA": "COZINHA",
      "EMAIL": "confecção@grupodass.com.br"
    },
    {
      "PATRIMONIO": "103803",
      "EQUIPAMENTO": "AR CONDICIONADO",
      "NOME": "AR CONDICIONADO",
      "MODELO": "K7",
      "TIPO": "CONVENCIONAL",
      "MARCA": "ELGIN",
      "RESPONSAVEL": "",
      "TENSAO": "220 V",
      "FLUIDO": "R410",
      "BTUS": "60K BTUS",
      "SETOR": "IMPRESSÃO DIGITAL",
      "SALA": "IMPRESSÃO DIGITAL",
      "EMAIL": "confecção@grupodass.com.br"
    },
    {
      "PATRIMONIO": "103806",
      "EQUIPAMENTO": "AR CONDICIONADO",
      "NOME": "AR CONDICIONADO",
      "MODELO": "K7",
      "TIPO": "CONVENCIONAL",
      "MARCA": "ELGIN",
      "RESPONSAVEL": "",
      "TENSAO": "220 V",
      "FLUIDO": "R410",
      "BTUS": "60K BTUS",
      "SETOR": "IMPRESSÃO DIGITAL",
      "SALA": "IMPRESSÃO DIGITAL",
      "EMAIL": "confecção@grupodass.com.br"
    },
    {
      "PATRIMONIO": "103808",
      "EQUIPAMENTO": "AR CONDICIONADO",
      "NOME": "AR CONDICIONADO",
      "MODELO": "K7",
      "TIPO": "CONVENCIONAL",
      "MARCA": "ELGIN",
      "RESPONSAVEL": "",
      "TENSAO": "220 V",
      "FLUIDO": "R410",
      "BTUS": "60K BTUS",
      "SETOR": "IMPRESSÃO DIGITAL",
      "SALA": "IMPRESSÃO DIGITAL",
      "EMAIL": "confecção@grupodass.com.br"
    },
    {
      "PATRIMONIO": "99977",
      "EQUIPAMENTO": "AR CONDICIONADO",
      "NOME": "AR CONDICIONADO",
      "MODELO": "SPLIT",
      "TIPO": "INVERTER",
      "MARCA": "MIDEA",
      "RESPONSAVEL": "",
      "TENSAO": "220 V",
      "FLUIDO": "R410",
      "BTUS": "12K BTUS",
      "SETOR": "SALA TINTAS",
      "SALA": "SALA TINTAS",
      "EMAIL": "confecção@grupodass.com.br"
    },
    {
      "PATRIMONIO": "125252",
      "EQUIPAMENTO": "AR CONDICIONADO",
      "NOME": "AR CONDICIONADO",
      "MODELO": "",
      "TIPO": "",
      "MARCA": "",
      "RESPONSAVEL": "",
      "TENSAO": "220 V",
      "FLUIDO": "",
      "BTUS": "",
      "SETOR": "LABORATORIO",
      "SALA": "LABORATORIO",
      "EMAIL": "confecção@grupodass.com.br"
    }
  ];

  int sucessos = 0;
  int erros = 0;

  try {
    for (var i = 0; i < equipamentos.length; i++) {
      try {
        await firestore.collection(collectionName).add(equipamentos[i]);
        sucessos++;
        print(
            'Equipamento ${i + 1}/89 cadastrado - Patrimônio: ${equipamentos[i]['PATRIMONIO']}');
      } catch (e) {
        erros++;
        print('Erro ao cadastrar equipamento ${i + 1}: $e');
      }
    }

    return 'Importação concluída!\n\nTotal: 89\nSucessos: $sucessos\nErros: $erros';
  } catch (e) {
    return 'Erro na importação: $e';
  }
}
